### ISSUE TITLE
VM agents plugin can't wake up nodes those are suspended occassionally

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-vm-agents-plugin#201]
<p>Null exception occurs like below log</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Unexpected exception encountered <span class="code-keyword">while</span> provisioning agent ltaz-jenkins-node7ef250java.lang.NullPointerException        at com.microsoft.azure.vmagent.AzureVMCloud.getLockForAgent(AzureVMCloud.java:1017)        at com.microsoft.azure.vmagent.AzureVMCloud.lambda$provision$1(AzureVMCloud.java:682)        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)        at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)        at java.util.concurrent.FutureTask.run(FutureTask.java:266)        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)        at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748)  </pre>
</div></div>
<p><a href="https://github.com/jenkinsci/azure-vm-agents-plugin/blob/dev/src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java#L1016" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/azure-vm-agents-plugin/blob/dev/src/main/java/com/microsoft/azure/vmagent/AzureVMCloud.java#L1016</a></p>

<p>Could you please have a look this case?</p>

<p>Thank you. </p>
<i>[JENKINS-64112] created by kangjin98</i>

**Comment by timja** [comment]
I'm not able to reproduce this
