### ISSUE TITLE
VM failed to provision when use Pool Retention Strategy

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-vm-agents-plugin#225]
<p>When use pool retention strategy, most times VMs are failed to provision.</p>

<p>If use the same template settings, only change retention strategy to Idle retention strategy, then all vms can provisioned successfully(100%). </p>

<p>Retention time in hour: 24</p>

<p>Pool Size: 1</p>

<p>Only a few times, VMs can be provisioned successfully with pool retention strategy.</p>
<h1><a name="NodeProvisioningActivityforAzureTest%2Fjenkins%E2%80%A6"></a>Node ProvisioningActivity for Azure-Test/jenkins-…</h1>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">java.lang.Exception: Node ProvisioningActivity <span class="code-keyword">for</span> Azure-Test/jenkins-test/<span class="code-keyword">null</span> (229415501) has lost. Mark as failure at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask.cleanCloudStatistics(AzureVMAgentCleanUpTask.java:604) at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask.clean(AzureVMAgentCleanUpTask.java:622) at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask.access$200(AzureVMAgentCleanUpTask.java:73) at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask$3.call(AzureVMAgentCleanUpTask.java:632) at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask$3.call(AzureVMAgentCleanUpTask.java:629) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748)</pre>
</div></div>
<i>[JENKINS-56981] created by diwang</i>

**Comment by timja** [comment]
I think solved, given no feedback since 2019
