### ISSUE TITLE
Authentication with a certificate on service principal does not work

### ISSUE THREAD

**Issue by krische** [jenkinsci/azure-vm-agents-plugin#282]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.277.4
OS: Linux - 5.4.0-1046-azure
---
ace-editor:1.1
font-awesome-api:5.15.3-2
checks-api:1.7.0
snakeyaml-api:1.27.0
momentjs:1.1.1
echarts-api:5.1.0-2
mailer:1.34
pipeline-stage-step:2.5
azure-sdk:12.vc102aedd3c66
handlebars:3.0.8
jquery-detached:1.2.1
configuration-as-code:1.51
lockable-resources:2.10
script-security:1.77
workflow-cps:2.92
caffeine-api:2.9.1-23.v51c4e2c879c8
kubernetes-credentials:0.9.0
authentication-tokens:1.4
jackson2-api:2.12.3
scm-api:2.6.4
pipeline-input-step:2.12
jquery3-api:3.6.0-1
workflow-cps-global-lib:2.19
bouncycastle-api:2.20
popper-api:1.16.1-2
kubernetes-client-api:4.13.3-1
workflow-durable-task-step:2.39
workflow-basic-steps:2.23
pipeline-stage-view:2.19
plain-credentials:1.7
antisamy-markup-formatter:2.1
pipeline-build-step:2.13
workflow-scm-step:2.12
pipeline-model-extensions:1.8.4
cloudbees-folder:6.15
windows-slaves:1.8
docker-commons:1.17
command-launcher:1.6
git-server:1.9
branch-api:2.6.4
credentials:2.4.1
kubernetes:1.29.6
extended-read-permission:3.2
azure-credentials:182.v3ccd4a755864
matrix-auth:2.6.7
pipeline-model-api:1.8.4
workflow-step-api:2.23
icon-shim:3.0.0
git-client:3.7.1
jaxb:2.3.0.1
credentials-binding:1.24
structs:1.23
pipeline-model-declarative-agent:1.1.1
durable-task:1.36
workflow-multibranch:2.24
pipeline-milestone-step:1.3.2
workflow-job:2.40
variant:1.4
jdk-tool:1.5
metrics:4.0.2.7
workflow-support:3.8
display-url-api:2.3.5
trilead-api:1.0.13
git:4.7.1
ssh-credentials:1.18.1
apache-httpcomponents-client-4-api:4.5.13-1.0
bootstrap4-api:4.6.0-3
workflow-aggregator:2.6
pipeline-rest-api:2.19
docker-workflow:1.26
pipeline-model-definition:1.8.4
jsch:0.1.55.2
cloud-stats:0.27
junit:1.49
workflow-api:2.42
plugin-util-api:2.2.0
azure-vm-agents:780.v50d067d02f76
pipeline-graph-analysis:1.10
pipeline-stage-tags-metadata:1.8.4
matrix-project:1.18
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Official Docker image running in AKS with official helm chart
```

### Reproduction steps

1. Create the Microsoft Azure Service Principal Credential with the Client secret blank and instead using a Certificate
2. Attempt to create a new Azure VM Agents cloud instance.
3. Try to list existing resource groups

### Results

Expected result:

It should use the provided certificate with the Service Principal to perform Azure operations

Actual result:
Performing an operation (like listing available resource groups) fails with an exception: `java.lang.IllegalArgumentException: clientSecret is null or empty`. Full log entry below:

```
May 27, 2021 8:11:06 PM WARNING com.microsoft.azure.vmagent.AzureVMCloud$DescriptorImpl doFillExistingResourceGroupNameItems

Cannot list resource group name: 
java.lang.IllegalArgumentException: clientSecret is null or empty
	at com.microsoft.aad.msal4j.ClientSecret.<init>(ClientSecret.java:20)
	at com.microsoft.aad.msal4j.ClientCredentialFactory.createFromSecret(ClientCredentialFactory.java:27)
	at com.azure.identity.implementation.IdentityClient.lambda$getConfidentialClientApplication$3(IdentityClient.java:174)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:143)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8227)
	at reactor.core.publisher.Flux.blockLast(Flux.java:2518)
	at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:94)
	at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:50)
	at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:37)
	at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:106)
	at com.azure.resourcemanager.resources.fluentcore.utils.PagedConverter$PagedIterableImpl.iterator(PagedConverter.java:225)
	at com.microsoft.azure.vmagent.AzureVMCloud$DescriptorImpl.doFillExistingResourceGroupNameItems(AzureVMCloud.java:1139)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:92)
	at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:92)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:62)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:109)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:168)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:279)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
Also:   java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Flux.blockLast(Flux.java:2519)
		at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:94)
		at com.azure.core.util.paging.ContinuablePagedByItemIterable$ContinuablePagedByItemIterator.<init>(ContinuablePagedByItemIterable.java:50)
		at com.azure.core.util.paging.ContinuablePagedByItemIterable.iterator(ContinuablePagedByItemIterable.java:37)
		at com.azure.core.util.paging.ContinuablePagedIterable.iterator(ContinuablePagedIterable.java:106)
		at com.azure.resourcemanager.resources.fluentcore.utils.PagedConverter$PagedIterableImpl.iterator(PagedConverter.java:225)
		at com.microsoft.azure.vmagent.AzureVMCloud$DescriptorImpl.doFillExistingResourceGroupNameItems(AzureVMCloud.java:1139)
		at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
		at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
		at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
		at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
		at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
		at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:536)
		at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
		at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
		at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:281)
		at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
		at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:766)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:898)
		at org.kohsuke.stapler.Stapler.invoke(Stapler.java:694)
		at org.kohsuke.stapler.Stapler.service(Stapler.java:240)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
		at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
		at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
		at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
		at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:129)
		at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
		at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)
		at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
		at jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
		at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
		at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
		at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:153)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:92)
		at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
		at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
		at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
		at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
		at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
		at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:92)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218)
		at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
		at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
		at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
		at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:62)
		at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:97)
		at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:109)
		at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:168)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
		at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:51)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
		at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
		at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
		at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:36)
		at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
		at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
		at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
		at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
		at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
		at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
		at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
		at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
		at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
		at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
		at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
		at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
		at org.eclipse.jetty.server.Server.handle(Server.java:516)
		at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
		at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
		at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:279)
		at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
		at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
		at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
		at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
Caused: java.lang.RuntimeException: Max retries 3 times exceeded. Error Details: clientSecret is null or empty
	at com.azure.core.http.policy.RetryPolicy.lambda$attemptAsync$1(RetryPolicy.java:127)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
	at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onError(FluxPeekFuseable.java:903)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2062)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1862)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:157)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:81)
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2057)
	at reactor.core.publisher.Operators.complete(Operators.java:136)
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:45)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
	at reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1862)
	at reactor.core.publisher.MonoCacheTime.subscribeOrReturn(MonoCacheTime.java:157)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:52)
	at reactor.core.publisher.MonoDelaySubscription.accept(MonoDelaySubscription.java:33)
	at reactor.core.publisher.FluxDelaySubscription$DelaySubscriptionOtherSubscriber.onNext(FluxDelaySubscription.java:130)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:119)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by timja** [comment]
Did this work previously?

**Comment by krische** [comment]
Yes, it worked in version 774. I noticed it not working in version 780. I didn't get a chance to test it in each version in between yet.

**Comment by timja** [comment]
There was a bug in Jenkins core which prevented me from testing this scenario, I couldn't figure out how to get a certificate to work at the time, the bug was fixed in the credentials plugin recently: https://github.com/jenkinsci/credentials-plugin/pull/208

So this can be fixed now

**Comment by krische** [comment]
Thanks, and I figure it's worth noting that I can successfully "verify" the service principal credential when adding/updating it with a blank client secret. It's only when it actually gets "used" that it doesn't work.
