### ISSUE TITLE
When upgrading to the latest version of the plugin the service principle account will no longer connect to azure

### ISSUE THREAD

**Issue by limeman40** [jenkinsci/azure-vm-agents-plugin#314]
This is the error I see when trying to use the service principle account:

java.lang.IllegalStateException: More than one subscription found in your tenant. Please specify which one below is desired for resource management. 
 at com.azure.resourcemanager.resources.fluentcore.utils.ResourceManagerUtils.getDefaultSubscription(ResourceManagerUtils.java:135)
        at com.azure.resourcemanager.AzureResourceManager$AuthenticatedImpl.withDefaultSubscription(AzureResourceManager.java:343)
        at com.microsoft.jenkins.credentials.AzureResourceManagerRetriever.getAzureResourceManager(AzureResourceManagerRetriever.java:49)
        at com.microsoft.jenkins.credentials.AzureResourceManagerRetriever.getClient(AzureResourceManagerRetriever.java:35)
        at com.microsoft.jenkins.credentials.AzureResourceManagerCache.createClient(AzureResourceManagerCache.java:67)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:141)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2413)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2411)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2394)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
        at com.microsoft.jenkins.credentials.AzureResourceManagerCache.get(AzureResourceManagerCache.java:40)
        at com.microsoft.azure.vmagent.AzureVMCloud.getAzureClient(AzureVMCloud.java:958)
        at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask.cleanLeakedResources(AzureVMAgentCleanUpTask.java:354)
        at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask.cleanLeakedResources(AzureVMAgentCleanUpTask.java:329)
        at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask.clean(AzureVMAgentCleanUpTask.java:630)
        at com.microsoft.azure.vmagent.AzureVMAgentCleanUpTask.lambda$execute$1(AzureVMAgentCleanUpTask.java:640)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

Yet in my secrets I am setting which environment I wish to build VMs on.  If I change my plugin back to a month ago:

789.va0c40e4d0070

It starts working again unsure what other level of details you need to look into this.  Please let me know if you need me to provide any further details .

**Comment by timja** [comment]
Thanks, reproduced, my test setup only had one subscription before
